### ISSUE TITLE
[DOCS] Enhancement of text.

### ISSUE THREAD

**Issue by akansha-02** [07sumit1002/CabRental#259]
**Describe the documentation update**
The text documentation is not properly visible causing problem for the mobile user to read it.

**Why is this needed?**
The font style  , size etc. can be changed to make it look elegant. 
It will also increase the intereactiveness of the page.

**Additional context**
![Screenshot 2024-10-06 233951](https://github.com/user-attachments/assets/39b7889b-9f79-47ec-aa2f-55fbb3755059)
![Screenshot 2024-10-06 234004](https://github.com/user-attachments/assets/3b2de11f-f2fc-4e49-a919-af9650391e71)
Kindly refer to the above images for the issues I have mentioned.

Please assign me this issue under Hacktoberfest and gssoc '24 extended.

**Comment by akansha-02** [comment]
Please assign me this issue under Hacktoberfest and gssoc '24 extended.

**Comment by akbatra567** [comment]
Hey @akansha-02, 
Assigned you the issue, also this issue is tagged incorrectly it is not a documentation issue, it is more of a bug or ui/ux issue. 

Also, let's try to restrict the scope of the card. 

So make the website more mobile friendly, as there is some other issue which handles the responsiveness of the website, it would be fine if you limit your scope to only mobile device screen size and you can avoid fixing the whole website responsiveness.
